# Generated by Django 5.0.4 on 2024-04-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
